### ISSUE TITLE
NatsAutoConfiguration.class breaks (@WebMvcTest) tests

### ISSUE THREAD

**Issue by mythicallage** [nats-io/spring-nats#44]
### Context case:
I'm trying to test only one controller like:

```java
@WebMvcTest(UserController.class)
public class UserControllerTest {
// some tests here
}
```
And then I've got like this:

```bash
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'natsConnection' defined in class path resource [io/nats/spring/boot/autoconfigure/NatsAutoConfiguration.class]: Failed to instantiate [io.nats.client.Connection]: Factory method 'natsConnection' threw exception with message: Unable to connect to NATS servers: [nats://localhost:4222]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)
```

The spring boot 3.x only has dependencies **with default beans**:

```maven
        <dependency>
            <groupId>io.nats</groupId>
            <artifactId>jnats</artifactId>
            <version>2.18.1</version>
        </dependency>

        <dependency>
            <groupId>io.nats</groupId>
            <artifactId>nats-spring</artifactId>
            <version>0.5.7</version>
        </dependency>
```

### Solve. I have to write tests every time like below:

```java
@WebMvcTest(value = UserController.class, excludeAutoConfiguration = NatsAutoConfiguration.class)
public class UserControllerTest {
// some tests here
}
```

**Comment by kunalvarpe** [comment]
I am able to run controller test without exclude, but I am using spring boot 3.2.x. I believe for spring boot 3.x `nats-spring` version needs upgrade to `0.6.0-3.1`.  The point I wanted to make here is with supported release the issue in no longer exists.

**Comment by kunalvarpe** [comment]
Closing the issue as it is no longer reproducible with spring boot compatible nats library.
